language: python
python:
  - "2.7"
install:
  - pip install .[dev]
  - pip install -r requirements.txt
script: nose2 --with-coverage
after_sucess:
  - CODECLIMATE_REPO_TOKEN=$CODECLIMATE_REPO_TOKEN codeclimate-test-reporter
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_API_KEY
  app:
    develop: isoprene-pumpjack-staging
    master: isoprene-pumpjack