language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
script:
  - nose2 --with-coverage
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - codeclimate-test-reporter
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then curl -sSL https://download.sourceclear.com/ci.sh | bash; fi
deploy:
  - provider: heroku
    api_key:
      secure: $HEROKU_API_KEY
    app:
      develop: isoprene-pumpjack-staging
      master: isoprene-pumpjack
  - provider: pypi
    skip_upload_docs: true
    distributions: sdist
    user: tommilligan
    password: $PYPI_PASSWORD
    on:
      branch: master
      tags: true 
      condition: $TRAVIS_PYTHON_VERSION = "2.7"
notifications:
  email: false

