language: python
python:
  - "2.7"
  # PyPy versions
  - "pypy"
# command to install dependencies
install:
  - pip install .
  - pip install -r requirements.txt
# command to run tests
script: nose2 --with-coverage
after_sucess:
  - CODECLIMATE_REPO_TOKEN=$CODECLIMATE_REPO_TOKEN codeclimate-test-reporter
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_API_KEY
